### ISSUE TITLE
Code fails with lib kriswallsmith/buzz  0.17.0

### ISSUE THREAD

**Issue by ismail1432** [sensiolabs/SensioLabsConnectBundle#24]
The code doesn't works with `kriswallsmith/buzz: 0.17.0` because they removed many things used by the bundle.
For example, the `APICollector` use `ListenerInterface` that was removed.

You can see others changes in the (change log)[https://github.com/kriswallsmith/Buzz/blob/master/CHANGELOG.md]

There is no problem with this version `kriswallsmith/buzz": "0.16.1`

IMHO we should change the downloaded version in a 1st time and update code in a second time.

**Comment by fabpot** [comment]
I think this one can be closed as fixed by sensiolabs/connect#62. @ismail1432 Can you confirm?

**Comment by ismail1432** [comment]
Closed as fixed by sensiolabs/connect#62
